Support HyperlinkedModelSerializer
By providing the ``request`` object to the jwt_response_payload_handler we can use ``HyperlinkedModelSerializer`` for a "UserSerializer" and prevent the following errror:

{{{
AssertionError: `HyperlinkedIdentityField` requires the request in the serializer context. Add `context={'request': request}` when instantiating the serializer.
}}}